# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160823_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='photo',
            field=models.ImageField(default='img/users/no-img.png', upload_to='img/users/'),
        ),
    ]
