# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20160829_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesstructure',
            old_name='monthly_fees',
            new_name='fees_amount',
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='fees_structure_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly')], default='Monthly', max_length=256),
            preserve_default=False,
        ),
    ]
